version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0

    steps:
      - checkout

      # special step to restore the dependency cache
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Setup Dependencies
          command: npm install

      # special step to save the dependency cache
      - save_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            
      # run tests
      - run:
          name: Run Test and Coverage
          command: |
            npm test -- --coverage
